- name: Make sure XDG Base Directory Specification environment variables are defined
  lineinfile:
    path: /etc/profile
    state: present
    line: "{{ item }}"
  with_items:
    - export XDG_CONFIG_HOME=$HOME/.config
    - export XDG_CACHE_HOME=$HOME/.cache
    - export XDG_DATA_HOME=$HOME/.local/share
    - export XDG_DATA_DIRS=/usr/local/share:/usr/share
    - export XDG_CONFIG_DIRS=/etc/xdg
  become: yes

- name: Make sure XDG directories exists
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - ~/.cache
    - ~/.local/share
    - ~/.config
    - ~/.config/git
    - ~/.config/nvim

- name: Install packages
  package:
    name:
      - base-devel
      - fzf
      - git
      - neofetch
      - neovim
      - tree
      - tigervnc
      - lxqt
      - noto-fonts
      - noto-fonts-cjk
      - noto-fonts-emoji
      - avahi
      - nss-mdns
    state: present
  become: yes

- name: Create user to aur_builder
  user:
    name: aur_builder
    group: wheel
  become: yes

- name: Configure user aur_builder
  lineinfile:
    path: /etc/sudoers.d/11-install-aur_builder
    line: 'aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
    validate: 'visudo -cf %s'
  become: yes

- name: Install AUR packages
  aur:
    use: makepkg
    name:
      - ghq
      - gitflow-avh
  become: yes
  become_user: aur_builder

# dotfiles
- name: Ensure dotfiles (template) are placed
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: gitconfig.j2, dest: ~/.config/git/config }

- name: Ensure dotfiles (files) are symlinked
  file:
    src: "{{ ansible_env.PWD }}/roles/base/files/{{ item.filename }}"
    dest: "{{ item.dest_dir }}/{{ item.filename }}"
    state: link
  with_items:
    - { filename: init.vim, dest_dir: ~/.config/nvim }
    - { filename: ignore, dest_dir: ~/.config/git }

# Setup Neovim
- name: Ensures autoload dir exists
  file:
    path: ~/.local/share/nvim/site/autoload
    state: directory

- name: Download Vim-Plug script
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.local/share/nvim/site/autoload/plug.vim

- name: Install Vim-Plug plugins
  shell: nvim --headless +PlugInstall +qall
  args:
    creates: ~/.config/nvim/plugged
    executable: /bin/bash
    warn: no

# Setup Avahi
# https://wiki.archlinux.jp/index.php/Avahi#.E3.83.9B.E3.82.B9.E3.83.88.E5.90.8D.E3.81.AE.E8.A7.A3.E6.B1.BA
- name: Make sure a service unit is running
  systemd:
    state: started
    name: avahi-daemon.service
  become: yes

#  「hosts」の行に関して、「mdns_minimal」が入っていない場合のみ
# 「resolve\s」の手前のスペースを
# 「 mdns_minimal [NOTFOUND=return] 」に置き換える。
- name: Make sure 'mdns_minimal [NOTFOUND=return]' exists in the line starts with 'hosts'
  replace:
    path: /etc/nsswitch.conf
    regexp: '(?!.*mdns_minimal)(hosts:.*)(\s)(resolve\s.*)'
    replace: '\1 mdns_minimal [NOTFOUND=return] \3'
  become: yes

